1. Create a NumPy array and make a copy of it. Modify the original array and print both
the original and copied arrays.

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
x=a.copy()
x[2]=15
print(x)
print("-----------------------------------")
print(a)

[ 1  2 15  4  5  6  7  8  9 10]
-----------------------------------
[ 1  2  3  4  5  6  7  8  9 10]


2. Create a view of a NumPy array. Modify the view and print both the original and the
view. How do the results compare to using a copy?

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
x=a.view()
x[3]=18
print(x)
print("-----------------------------------")
print(a)

[ 1  2  3 18  5  6  7  8  9 10]
-----------------------------------
[ 1  2  3 18  5  6  7  8  9 10]


3. Explain the difference between array.copy() and array.view() in NumPy. Provide an
example to illustrate the difference.

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
x=a.copy()
y=a.view()
print(x.base)
print(y.base)


None
[ 1  2  3  4  5  6  7  8  9 10]


4. Create a 2D NumPy array and generate a view that represents only the first row.
Modify this view and print the changes in both the original array and the view.

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=a.view()
print(a[0])
print(b[0])

[1 2 3]
[1 2 3]


5. Create a NumPy array and another array by slicing the first array. Check whether the
second array is a copy or a view of the first array.

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9])
b=np.array(a[1:5])
print(a)
print("-------------------")
print(b)
print(b.base)

[1 2 3 4 5 6 7 8 9]
-------------------
[2 3 4 5]
None


6. Use the np.may_share_memory() function to check if two arrays share the same
memory. Provide an example.

In [ ]:
a=np.array([1,2,3,4,5])
b=a.view()
print(np.may_share_memory(a,b))

True


7. Create a NumPy array, then use the reshape() function on it. Check whether the
reshaped array is a view or a copy.

In [ ]:
a=np.array([1,2,3,4,5,6,7,8])
b=a.reshape(2,4)
print(b)
print(b.base)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


8. Create a NumPy array and print its shape. Then reshape it to another valid shape and
print the new shape.

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a.shape)
b=a.reshape(3,3)
print(b)

(9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


9. Given a 1D array of length 12, reshape it into a 2D array with 3 rows. Then, reshape it
into a 3D array. Print the shapes at each step.

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b=a.reshape(3,4)
print(a)
print(a.shape)
print("-------------------")
print(b)
print(b.shape)
print("-------------------")
c=b.reshape(3,2,2)
print(c)
print(c.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
-------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
-------------------
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)


10.Create a 3x4 matrix and then reshape it into a 2x6 matrix. Verify if reshaping changes
the data content.

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a.reshape(2,6)
print(a)
print("-----------------------")
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-----------------------
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


11.Reshape a 2D array into a 3D array. Then reshape it back to its original 2D shape.

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8]])
b=a.reshape(2,2,2)
print(b)
print("-----------------")
c=b.reshape(2,4)
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
-----------------
[[1 2 3 4]
 [5 6 7 8]]


12.Given a 4x4 matrix, reshape it into a 2D array with dimensions 2x8. Then, reshape it
back to 4x4.

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],
            [9,10,11,12],[13,14,15,16]])
b=a.reshape(2,8)
print(b)
print("-------------------")
c=b.reshape(4,4)
print(c)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
-------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


13.Create a 3D array and flatten it into a 1D array using reshape(-1).

In [ ]:
a=np.array([[[1,2,3,4],[5,6,7,8]]])
b=a.reshape(-1)
print(a)
print("-------------------")
print(b)

[[[1 2 3 4]
  [5 6 7 8]]]
-------------------
[1 2 3 4 5 6 7 8]


14.Create a 3x3 matrix and iterate over its elements row by row.

In [3]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
for x in a:
  print(x)

[1 2 3]
[4 5 6]
[7 8 9]


15.Create a 2D array. Print index of each element including that element.

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8]])
for idx,i in np.ndenumerate(a):
  print(idx,i)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


16.Iterate over a 3D array and print each element, along with its corresponding index.

In [ ]:
a=np.array([[[1,2,3],[4,5,6]],
             [[7,8,9],[10,11,12]]])
for idx,x in np.ndenumerate(a):
  print(idx,x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


17.Create a 2D NumPy array and use np.nditer() to iterate over it. Print each element.

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
for x in np.nditer(a):
  print(x)

1
2
3
4
5
6


18.Create a 3D array. Print each element and its corresponding index.

In [ ]:
a=np.array([[[1,2,3],[4,5,6]],
            [[7,8,9],[10,11,12]]])
for idx,x in np.ndenumerate(a):
  print(idx,x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


19.Create a 6D array and use nditer() and print each element .

In [6]:
a=np.array([1,2,3,4,5],ndmin=6)
print(a)
print("_____________________")
for x in np.nditer(a):
  print(x)

[[[[[[1 2 3 4 5]]]]]]
_____________________
1
2
3
4
5


20.Create a 2D integer array and use nditer() to iterate over it as if it were an float array.
Print the elements.

In [7]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in np.nditer(a,flags=["buffered"],op_dtypes=[float]):
  print(x)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


21.Use nditer() to iterate over a mixed data type array, where some elements are floats
and others are integers.

In [ ]:
a=np.array([1,1.2,5.4,5,6.2,8,5])
for x in np.nditer(a):
  print(x)

1.0
1.2
5.4
5.0
6.2
8.0
5.0


22.Create a 2D array and iterate over it using nditer() with op_dtypes set to different
types. Observe and explain the results.

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
for x in np.nditer(a,flags=["buffered"],op_dtypes=['S']):
  print(x)  # after using nditer()the array data type changed integer to string

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'


23.Create a 1D array of 10 elements and iterate over it using a step size of 2. Print the
accessed elements.

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
for x in np.nditer(a[::2]):
  print(x)

1
3
5
7
9


24.Iterate over every second element of a 2D array along with indices of the elements

In [ ]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
b=a[:,1:2]
for idx,x in np.ndenumerate(b):
  print(idx,x)

(0, 0) 2
(1, 0) 7


25.Create a 3D array and iterate over every second element. Print the elements accessed
in each step along with indices of element.


In [ ]:
a=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]])
print(a)
print("-----------------")
for idx,x in np.ndenumerate(a[:,:,1:2]):
  print(idx,x)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]]
-----------------
(0, 0, 0) 2
(0, 1, 0) 6
(0, 2, 0) 10
(0, 3, 0) 14
